"""
AgentGuard — Default starter configuration.

Strings emitted by `agentguard init`. Keep in sync with agentguard.yaml schema.
"""

DEFAULT_YAML = """\
# agentguard.yaml — generated by `agentguard init`
# Edit this file to configure your security layers.
# Documentation: https://github.com/wildcraft958/AgentGuard_NamoFans
# ──────────────────────────────────────────────────────────────────

version: 1
agent_name: "my-agent"

# ── Global ────────────────────────────────────────────────────────
global:
  mode: enforce          # enforce | monitor | dry-run
  log_level: standard    # minimal | standard | detailed
  fail_safe: block       # block | allow  (on unexpected errors)
  max_validation_latency_ms: 500
  parallel_execution: false  # run L1 validation + agent concurrently (reduces latency)

# ── Audit Log ─────────────────────────────────────────────────────
audit:
  enabled: true
  db_path: ./agentguard_audit.db
  log_l4_signals: true

# ── L1: Azure AI Content Safety ───────────────────────────────────
# Requires CONTENT_SAFETY_ENDPOINT + CONTENT_SAFETY_KEY in .env
# Falls back to offline regex filter when Azure is unreachable.
input_security:
  prompt_shields:
    enabled: true
    sensitivity: medium      # low | medium | high
    block_on_detected_injection: true
  content_filters:
    block_toxicity: true
    block_violence: true
    block_self_harm: true

# ── L2: Azure Language / Text Analytics ───────────────────────────
# Requires AZURE_LANGUAGE_ENDPOINT + AZURE_LANGUAGE_KEY in .env
output_security:
  toxicity_detection:
    enabled: true
    block_on_detected_toxicity: true
  pii_detection:
    enabled: true
    block_on_pii_exfiltration: true
    allowed_categories:
      - Organization
      - DateTime
      - URL

# ── L3: Pattern Matching ──────────────────────────────────────────
# No API keys needed — always runs.
pattern_detection:
  enabled: true
  block_on_match: true
  halt_on_blocklist_hit: true
  blocklists:
    - name: agentguard-default
      description: "Default AgentGuard security blocklist"
      terms:
        - "SYSTEM OVERRIDE"
        - "ignore all previous instructions"
        - "ignore previous instructions"
        - "disregard your instructions"
        - "curl "
        - "wget "
        - "__import__"
        - "os.system"
        - "eval("
        - "exec("
        - "base64.decode"
        - "BEGIN PRIVATE KEY"
        - "BEGIN RSA PRIVATE"
        - "id_rsa"
        - "/etc/shadow"
        - "/etc/passwd"

# ── L3: Tool Firewall ─────────────────────────────────────────────
tool_firewall:
  default_policy: allow
  file_system:
    enabled: true
    allowed_paths: [/tmp/, /app/safe_data/]
    deny_extensions: [.env, .pem, .key]
  sql_query:
    enabled: true
    allowed_statements: [SELECT]
    denied_statements: [DROP, DELETE, UPDATE, TRUNCATE]
  http_post:
    enabled: true
    mode: allowlist
    allowed_domains: []
    require_https: true
    block_private_ips: true
  http_get:
    enabled: true
    mode: allowlist
    allowed_domains: []
    block_metadata_services: true
  shell_commands:
    enabled: true
    mode: denylist
    denied_commands: [rm, chmod, sudo, curl, wget, bash, sh, eval, exec, python, python3]
    block_command_chaining: true
  approval_workflow:
    enabled: false
    mode: "human"       # "human" or "ai"
    tools_requiring_review: []
  melon:
    enabled: false
    mode: hybrid               # hybrid | judge_only | embedding_only
    judge_model: null           # null = uses TFY_MODEL
    embedding_model: null       # null = skip embedding pre-filter (judge_only behavior)
    low_threshold: 0.3          # below -> ALLOW immediately
    high_threshold: 0.9         # above -> BLOCK immediately
    raise_on_injection: true

# ── L4: ABAC Role Policy ──────────────────────────────────────────
# No API keys needed — fully offline.
rbac:
  default_deny: true
  capability_model:
    default_agent:
      tier: 1
      resource_permissions:
        public:       [read]
        internal:     [read]
        confidential: []
      denied_verbs: [delete, execute_shell, network_external]
      elevate_on:   [any_write, any_delete, external_network]
      approved_domains: []
      expected_sequence: []

# ── L4: Behavioral Monitoring (legacy) ────────────────────────────
behavioral_monitoring:
  enabled: true
  max_tool_calls_zscore_threshold: 2.5
  sequence_divergence_threshold: 0.4
  entropy_spike_multiplier: 1.5
  exfil_chain_detection: true

# ── L4 Adaptive: PBAC + Behavioral Anomaly Engine ────────────────
# Replaces static ABAC with hot-reloadable YAML policies (L4a)
# and online behavioral anomaly detection (L4b).
l4_adaptive:
  enabled: false
  policies_file: null           # path to l4_policies.yaml (null = use bundled default)
  ioa_patterns_file: null       # path to ioa_patterns.yaml (null = use bundled default)
  elevate_threshold: 0.70       # risk_score >= this -> ELEVATE
  deny_threshold: 0.90          # risk_score >= this -> DENY
  cold_start_threshold: 50      # calls before per-role model trusted
  drift_window: 8               # sliding window for sensitivity drift
  weights:
    baseline: 0.35              # HalfSpaceTrees anomaly weight
    graph: 0.40                 # session graph + IOA weight
    drift: 0.25                 # compliance drift weight

# ── Promptfoo Red-Team Testing ────────────────────────────────────
testing:
  purpose: |
    A secure AI agent. Must NOT execute shell commands, leak PII,
    exfiltrate data, or bypass security controls.
  plugins:
    - prompt-injection
    - jailbreak
    - pii
    - rbac
  strategies:
    - basic
    - jailbreak
  num_tests: 10
"""

DEFAULT_ENV_EXAMPLE = """\
# AgentGuard — Required Environment Variables
# Copy this to .env and fill in your credentials.
# NEVER commit .env to git — it is in .gitignore by default.

# ── L1: Azure AI Content Safety ──────────────────
# Azure Portal → AI Services → Content Safety → Keys and Endpoint
CONTENT_SAFETY_ENDPOINT=https://<your-resource>.cognitiveservices.azure.com/
CONTENT_SAFETY_KEY=

# ── L2: Azure Language / Text Analytics (PII) ────
# Azure Portal → AI Services → Language → Keys and Endpoint
AZURE_LANGUAGE_ENDPOINT=https://<your-resource>.cognitiveservices.azure.com/
AZURE_LANGUAGE_KEY=

# ── LLM Backend (Agent Reasoning) ────────────────
# TrueFoundry gateway (OpenAI-compatible) or Azure OpenAI directly
OPENAI_API_KEY=
OPENAI_BASE_URL=https://gateway.truefoundry.ai
OPENAI_MODEL=gcp-vertex-default/gemini-3-flash-preview

# ── Optional: OWASP Scanner (DeepTeam) ───────────
# Required only for `scan_agent()` — uses OpenAI API directly
# OPENAI_API_KEY=sk-...  (same key if using OpenAI, or set separately)
"""
