"""
AgentGuard — Promptfoo Python provider bridge.

This module is the glue between Promptfoo's red-team harness and any agent
function — guarded or unguarded.

Resolution order for target function:
1. Check _AGENT_REGISTRY for agent_name derived from AGENTGUARD_AGENT_NAME option
   or from agent_name field in AGENTGUARD_CONFIG yaml (for @guard_agent agents).
2. Fall back to AGENTGUARD_FUNCTION env var / option — load that function from
   the AGENTGUARD_AGENT_MODULE file (for unguarded agents).
3. Return an error output if neither resolves.

Usage as standalone Promptfoo provider (user-authored promptfooconfig.yaml):
    providers:
      - id: "python:src/agentguard/promptfoo_bridge.py"
        config:
          AGENTGUARD_CONFIG: src/agentguard.yaml
          AGENTGUARD_AGENT_MODULE: test_bots/my_agent.py
          AGENTGUARD_FUNCTION: run   # for unguarded agents

Usage via CLI (auto-generated config):
    agentguard test --config src/agentguard.yaml --module test_bots/my_agent.py
"""

import asyncio
import importlib.util
import inspect
import logging
import os
import sys

logger = logging.getLogger("agentguard.promptfoo_bridge")


def _load_module_from_path(module_path: str):
    """Dynamically import a Python file and return the module object."""
    module_path = os.path.abspath(module_path)
    spec = importlib.util.spec_from_file_location("_agentguard_target", module_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot load module from: {module_path}")
    mod = importlib.util.module_from_spec(spec)
    # Insert module directory into sys.path so relative imports work
    module_dir = os.path.dirname(module_path)
    if module_dir not in sys.path:
        sys.path.insert(0, module_dir)
    spec.loader.exec_module(mod)
    return mod


def _resolve_agent_name(options: dict) -> str | None:
    """
    Determine the agent_name to look up in _AGENT_REGISTRY.

    Priority:
    1. AGENTGUARD_AGENT_NAME option
    2. agent_name field in AGENTGUARD_CONFIG yaml
    """
    # Direct override
    if options.get("AGENTGUARD_AGENT_NAME"):
        return options["AGENTGUARD_AGENT_NAME"]

    # Read from config file
    config_path = options.get("AGENTGUARD_CONFIG")
    if config_path and os.path.exists(config_path):
        try:
            import yaml
            with open(config_path, "r") as f:
                raw = yaml.safe_load(f) or {}
            name = raw.get("agent_name")
            if name:
                return name
        except Exception as e:
            logger.debug("Could not read agent_name from config: %s", e)

    return None


def _load_module_if_needed(options: dict):
    """
    If AGENTGUARD_AGENT_MODULE is set and not already loaded, load the module.
    This triggers @guard_agent decorators at module level, populating _AGENT_REGISTRY.
    """
    module_path = options.get("AGENTGUARD_AGENT_MODULE")
    if not module_path:
        return None
    try:
        return _load_module_from_path(module_path)
    except Exception as e:
        logger.warning("Failed to load agent module '%s': %s", module_path, e)
        return None


def call_api(prompt: str, options: dict, context: dict) -> dict:
    """
    Promptfoo Python provider entry point.

    Args:
        prompt: The adversarial prompt generated by Promptfoo.
        options: Provider config dict (AGENTGUARD_CONFIG, AGENTGUARD_AGENT_MODULE, etc.)
        context: Promptfoo context (unused currently).

    Returns:
        {"output": str} — Promptfoo expects this shape.
    """
    from agentguard.decorators import _AGENT_REGISTRY

    # Step 1: Load module (populates _AGENT_REGISTRY via @guard_agent decorators)
    mod = _load_module_if_needed(options)

    # Step 2: Try to resolve via registry
    agent_name = _resolve_agent_name(options)
    if agent_name and agent_name in _AGENT_REGISTRY:
        func, _config, param, output_field = _AGENT_REGISTRY[agent_name]
        return _invoke(func, prompt, param, output_field)

    # Step 3: Fall back to AGENTGUARD_FUNCTION
    function_name = options.get("AGENTGUARD_FUNCTION")
    if function_name and mod is not None:
        func = getattr(mod, function_name, None)
        if func is not None:
            return _invoke(func, prompt, param_name=None, output_field=None)

    # Step 4: Nothing found
    logger.error(
        "No agent resolved. Set AGENTGUARD_AGENT_NAME / AGENTGUARD_FUNCTION in provider config."
    )
    return {"output": "[ERROR] No agent found. Check AGENTGUARD_AGENT_NAME or AGENTGUARD_FUNCTION."}


def _invoke(func, prompt: str, param_name: str | None, output_field: str | None) -> dict:
    """Call the target function with prompt, handle async, extract output field."""
    try:
        if param_name:
            call = func(**{param_name: prompt})
        else:
            call = func(prompt)

        # Handle async agent functions
        if inspect.iscoroutinefunction(func):
            result = asyncio.run(call)
        else:
            result = call

        if isinstance(result, dict) and output_field:
            output = result.get(output_field, str(result))
        else:
            output = str(result)

        return {"output": output}
    except Exception as e:
        return {"output": f"[BLOCKED] {type(e).__name__}: {e}"}
